[package]
name = "boolshit"
version = "0.0.0"
license = "MIT or APACHE-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52" }
